"""test

Revision ID: 3313d6d8fc42
Revises: 4227186e7732
Create Date: 2026-06-15 13:53:00.919437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3313d6d8fc42'
down_revision: Union[str, Sequence[str], None] = '4227186e7732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_isbn_key'), 'book', type_='unique')
    op.add_column('book_review', sa.Column('test', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('uq_book_review_book_user'), 'book_review', type_='unique')
    op.drop_constraint(op.f('uq_book_translations_book_lang'), 'book_translations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_book_translations_book_lang'), 'book_translations', ['book_id', 'lang'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_book_review_book_user'), 'book_review', ['book_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('book_review', 'test')
    op.create_unique_constraint(op.f('book_isbn_key'), 'book', ['isbn'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
