"""fix users_library schema

Revision ID: 09ca215fc426
Revises: 5482c1231b50
Create Date: 2026-06-17 14:42:25.746685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ca215fc426'
down_revision: Union[str, Sequence[str], None] = '5482c1231b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('users_library', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_library_user_id'), table_name='users_library')
    op.drop_index(op.f('ix_users_library_book_book_id'), table_name='users_library_book')
    op.drop_constraint(op.f('users_library_book_book_fkey'), 'users_library_book', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_library_book_book_fkey'), 'users_library_book', 'book', ['book_id'], ['id'], referent_schema='catalog', ondelete='CASCADE')
    op.create_index(op.f('ix_users_library_book_book_id'), 'users_library_book', ['book_id'], unique=False)
    op.create_index(op.f('ix_users_library_user_id'), 'users_library', ['user_id'], unique=False)
    # ### end Alembic commands ###
