global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: auth
    static_configs:
      - targets: ['auth:8000']

  - job_name: catalog
    static_configs:
      - targets: ['catalog:8000']

  - job_name: audio
    static_configs:
      - targets: ['audio:8000']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
