"""test

Revision ID: 16b31b6f1c09
Revises: aa4c7026c2ad
Create Date: 2026-06-15 13:39:09.402888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b31b6f1c09'
down_revision: Union[str, Sequence[str], None] = 'aa4c7026c2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('test', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'test')
    # ### end Alembic commands ###
